<a href="https://colab.research.google.com/github/Sabrina-Hendricks/DS4002-Group13-Project2/blob/main/Scripts/Project2MI2EDA_kiera.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Import data from Github

In [9]:
url = 'https://raw.githubusercontent.com/Sabrina-Hendricks/DS4002-Group13-Project2/refs/heads/main/Data/HealthCareOriginalData.csv'
df = pd.read_csv(url)
df.head()

,Unnamed: 0,2004,2004.1,2004.2,2004.3,2005,2005.1,2005.2,2005.3,2006,...,2022,2022.1,2022.2,2022.3,2023,2023.1,2023.2,2023.3,2024,2024.1
0,NaN,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,...,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2
1,Health care,1202.0,1226.0,1252.5,1275.0,1291.9,1309.5,1333.2,1347.6,1362.2,...,2753.8,2772.7,2835.3,2901.0,2983.3,3029.9,3068.6,3148.8,3233.6,3274.3
2,Outpatient services,575.6,585.0,594.6,601.8,613.0,621.1,628.1,635.4,639.2,...,1285.3,1306.6,1321.2,1346.6,1402.7,1420.2,1444.2,1481.1,1519.8,1554.7
3,Physician services (44),306.6,311.7,316.7,321.9,327.6,332.3,336.3,339.5,341.8,...,662.4,672.2,681.4,692.3,717.7,733.5,736.8,751.4,765.7,785.6
4,Dental services (45),81.0,82.5,84.2,85.4,86.7,87.7,88.1,89.0,89.7,...,158.6,160.4,163.4,165.7,170.7,171.3,173.3,175.4,180.2,183.9

In [13]:
df = df.set_index('Unnamed: 0')
df.head()

,2004,2004.1,2004.2,2004.3,2005,2005.1,2005.2,2005.3,2006,2006.1,...,2022,2022.1,2022.2,2022.3,2023,2023.1,2023.2,2023.3,2024,2024.1
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
NaN,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2,...,Q1,Q2,Q3,Q4,Q1,Q2,Q3,Q4,Q1,Q2
Health care,1202.0,1226.0,1252.5,1275.0,1291.9,1309.5,1333.2,1347.6,1362.2,1382.4,...,2753.8,2772.7,2835.3,2901.0,2983.3,3029.9,3068.6,3148.8,3233.6,3274.3
Outpatient services,575.6,585.0,594.6,601.8,613.0,621.1,628.1,635.4,639.2,647.5,...,1285.3,1306.6,1321.2,1346.6,1402.7,1420.2,1444.2,1481.1,1519.8,1554.7
Physician services (44),306.6,311.7,316.7,321.9,327.6,332.3,336.3,339.5,341.8,347.1,...,662.4,672.2,681.4,692.3,717.7,733.5,736.8,751.4,765.7,785.6
Dental services (45),81.0,82.5,84.2,85.4,86.7,87.7,88.1,89.0,89.7,91.0,...,158.6,160.4,163.4,165.7,170.7,171.3,173.3,175.4,180.2,183.9

KeyError: '[2] not found in axis'

In [ ]:
# Step 1: Reshape the data by using melt, categorizing by year, quarter, and spending
df_melted = df.melt(id_vars=['Unnamed: 0'], var_name='year_quarter', value_name='spending')

# Step 2: Split the 'year_quarter' into separate year and quarter columns
df_melted['year'] = df_melted['year_quarter'].apply(lambda x: x.split('.')[0])
df_melted['quarter'] = df_melted['year_quarter'].apply(lambda x: 'Q' + x.split('.')[1] if '.' in x else 'Q1')

# Step 3: Create category column for hierarchy - categorize based on Healthcare sections
df_melted['category'] = df_melted['Unnamed: 0'].apply(lambda x: 'Healthcare' if 'Health care' in x else
                                                    'Outpatient services' if 'Outpatient' in x or 'Physician' in x or 'Dental' in x or 'Paramedical' in x else
                                                    'Hospital and nursing home services' if 'Hospital' in x or 'Nursing' in x else x)

# Step 4: Remove unnecessary columns and rename as needed
df_final = df_melted[['category', 'Unnamed: 0', 'year', 'quarter', 'spending']]
df_final.rename(columns={'Unnamed: 0': 'subcategory'}, inplace=True)

# Now df_final will have a readable format with the category, subcategory, year, quarter, and spending
df_final.head()

TypeError: argument of type 'float' is not iterable